-- ==========================================================================
-- Cordo 63 — le carnet de tickets en production (Supabase / PostgreSQL)
-- La maquette garde les commandes dans le téléphone (localStorage). Pour que Clément reçoive
-- vraiment les demandes sur son téléphone à lui, on crée ce schéma dans un projet Supabase,
-- puis on renseigne CO.BACKEND dans js/co-commandes.js (url + clé publique « anon »).
--
-- Sécurité :
--   - le public (clé anon) peut SEULEMENT créer une demande (statut « envoyee ») ;
--   - il ne peut rien lire : le suivi passe par la fonction suivi(numero, telephone), qui ne
--     renvoie que l'état d'UN ticket, et seulement si le téléphone correspond ;
--   - Clément (utilisateur authentifié, lien magique par e-mail) lit et modifie tout.
-- ==========================================================================

create table if not exists public.commandes (
  numero      bigint generated by default as identity (start with 1001) primary key,
  cree_le     timestamptz not null default now(),
  statut      text not null default 'envoyee'
              check (statut in ('envoyee', 'recue', 'etabli', 'finitions', 'prete', 'rendue')),
  telephone   text not null,                 -- tel que saisi ; comparé sur les chiffres seuls
  donnees     jsonb not null,                -- la commande complète (objet, services, dépôt, client, photos réduites…)
  historique  jsonb not null default '[]'::jsonb,
  prix_final  numeric(8, 2),
  maj_le      timestamptz not null default now()
);

create index if not exists commandes_statut_idx on public.commandes (statut, cree_le desc);

alter table public.commandes enable row level security;

-- le public crée une demande, rien d'autre
drop policy if exists "public cree une demande" on public.commandes;
create policy "public cree une demande" on public.commandes
  for insert to anon
  with check (statut = 'envoyee' and length(telephone) between 6 and 25 and pg_column_size(donnees) < 600000);

-- l'atelier (Clément, connecté) voit et modifie tout
drop policy if exists "atelier lit" on public.commandes;
create policy "atelier lit" on public.commandes for select to authenticated using (true);
drop policy if exists "atelier modifie" on public.commandes;
create policy "atelier modifie" on public.commandes for update to authenticated using (true) with check (true);
drop policy if exists "atelier supprime" on public.commandes;
create policy "atelier supprime" on public.commandes for delete to authenticated using (true);

-- l'horodatage et l'historique suivent les changements d'état
create or replace function public.commandes_maj() returns trigger language plpgsql as $$
begin
  new.maj_le := now();
  if tg_op = 'INSERT' then
    new.historique := jsonb_build_array(jsonb_build_object('statut', new.statut, 'date', now()));
  elsif new.statut is distinct from old.statut then
    new.historique := coalesce(old.historique, '[]'::jsonb) || jsonb_build_object('statut', new.statut, 'date', now());
  end if;
  return new;
end $$;
drop trigger if exists commandes_maj on public.commandes;
create trigger commandes_maj before insert or update on public.commandes
  for each row execute function public.commandes_maj();

-- le suivi d'un ticket par le client : l'état seulement, jamais les coordonnées des autres
create or replace function public.suivi(p_numero bigint, p_telephone text)
returns table (numero bigint, statut text, historique jsonb, cree_le timestamptz)
language sql stable security definer set search_path = public as $$
  select c.numero, c.statut, c.historique, c.cree_le
  from public.commandes c
  where c.numero = p_numero
    and regexp_replace(c.telephone, '\D', '', 'g') ~ (right(regexp_replace(p_telephone, '\D', '', 'g'), 9) || '$')
    and length(regexp_replace(p_telephone, '\D', '', 'g')) >= 9
  limit 1;
$$;
revoke all on function public.suivi(bigint, text) from public;
grant execute on function public.suivi(bigint, text) to anon, authenticated;

-- (facultatif) les photos : un bucket privé « photos », écriture anonyme, lecture par l'atelier seulement.
-- (facultatif) prévenir Clément à chaque nouvelle demande : Database Webhook → e-mail / SMS (Brevo, Twilio…).
